### ISSUE TITLE
Empty should be supported for arrays of objects

### ISSUE THREAD

**Issue by ripienaar** [choria-io/scaffold#7]
Today the following will always inject a `[{}]` when no entries are being added:

```yaml
          - name: register_ports
            type: array
            empty: absent
            properties:
                - name: cluster
                  description: The cluster to export in
                  required: true
```

This should instead result in `[]`
